# Generated by Django 2.1rc1 on 2018-08-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '未通过')], default=0)),
                ('good_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('browse_num', models.IntegerField(default=0)),
            ],
        ),
    ]
